name: Stale

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['python']

    steps:
      - name: Close Stale Issues
        uses: actions/stale@v3
        with:
          start-date: 2021-02-01

          days-before-stale: 60
          days-before-issue-close: 7
          days-before-pr-close: 14

          stale-label: stale
          close-issue-label: wontfix
          close-pr-label: wontmerge

          exempt-issue-label: 'confirmed,enhancement'
          exempt-pr-label: 'on hold'

          stale-issue-message: >
            This issue has not been active since a lot of time. If you think it is still valid, feel free to reply with a simple comment.
            Without any update, I will close it in 7 days.
          stale-pr-message: >
            This pull request has not been active since a lot of time. If you're still working on it, please reply with a simple comment.
            Without any update, I will close it in 14 days.

          close-issue-message: >
            Closing this issue.
            If you think it should be considered, feel free to exhume it.
          close-pr-message: >
            Closing this PR, since it has not got activity for a while.
            If you're still working on it, feel free to reopen it.
